# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://www.kali.org/docs/virtualization/install-vagrant-guest-vm/

Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"

  config.vm.network "private_network", ip: '192.168.56.99' #, type: "dhcp"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 2048
    vb.cpus = 1
  end

  config.vm.provision "shell", inline: <<-EOF
    sudo apt update
    sudo apt install -y crowbar
    sudo apt install -y wget curl
    sudo hostnamectl set-hostname kaliaz
  EOF

end

# The box as "generic/debian11" provides a *base for Kali Linux*.
# We set the provider as VirtualBox and customize the VM settings to allocate 2048 MB of memory and 1 CPU.
# We configure a private network with DHCP and a synced folder.
# change hostname